[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
raydium_swap = "FZSd3d2QmSfyD5qr8UXY9x8poC2V3mKf8DVyf2BCDLzq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
